version: '3.8'

services:
  kali123:
    image: linuxserver/kali-linux:latest
    container_name: kali-123
    networks:
      - kalinet

  nginx:
    image: nginx:latest
    container_name: kali-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/routes:/etc/nginx/conf.d/routes:ro   # Added this line to mount routes folder
    ports:
      - "80:80"
    networks:
      - kalinet
    restart: unless-stopped   # Optional but good for production stability

networks:
  kalinet:
    driver: bridge
